# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 1666600000
  rpc_config:
    url: "https://api.harmony.one"
  start_block: 0
  contracts:
  - name: SweepStakesNFTs
    address:
    - 0xc71D7C069Ae96794c5d6d54ff04754D2832601c3
    handler: src/EventHandlers.ts
    events:
    - event: Enter(uint256 indexed _tokenId, uint256 _amount)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
    - event: Unstake(uint256 indexed _tokenId, uint256 _amount)
    - event: WinnerAssigned(uint256 winningTicket, uint256 indexed _winner, uint256 _amount)
    - event: Withdraw(uint256 indexed _tokenId, uint256 _amount)
rollback_on_reorg: false

