type ContractTotals {
  id: ID!
  totalPrizes: BigInt!
  balance: BigInt!
}

type User {
  id: ID!
  tokens: [Token!]! @derivedFrom(field: "userAddress")
}

type Token {
  id: ID!
  userAddress: String!
  balance: BigInt!
}

type SweepStakesNFTs_Enter {
  id: ID!
  _tokenId: BigInt!
  _amount: BigInt!
  userAddress: String!
}

type SweepStakesNFTs_Transfer {
  id: ID!
  from: String!
  to: String!
  tokenId: BigInt!
}

type SweepStakesNFTs_Unstake {
  id: ID!
  _tokenId: BigInt!
  _amount: BigInt!
  userAddress: String!
}

type SweepStakesNFTs_WinnerAssigned {
  id: ID!
  _winner: BigInt!
  _amount: BigInt!
  timestamp: Int!
  winnerAddress: String!
  winnerBalance: BigInt!
  totalBalance: BigInt!
}

type SweepStakesNFTs_Withdraw {
  id: ID!
  _tokenId: BigInt!
  _amount: BigInt!
}

